[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_anchor_hack = "8ncs7zruassJLwQ2xFPGfNx8qJ6ydDs57jNjmQBcc5xQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
